---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

base_dest: /tmp

ovn_kubernetes_dest: "{{ base_dest }}/ovn-kubernetes"
ovn_kubernetes_source_type: "tarball"
ovn_kubernetes_version: 0.3.0
ovn_kubernetes_url: "https://github.com/openvswitch/ovn-kubernetes/archive/v{{ ovn_kubernetes_version }}.tar.gz"
#ovn_kubernetes_source_type: "source"
#ovn_kubernetes_version: 456a0857956988f968bb08644c650ba826592ec1
#ovn_kubernetes_url: "https://github.com/openvswitch/ovn-kubernetes"

criproxy_dest: "{{ base_dest }}/criproxy"
criproxy_source_type: "binary"
criproxy_version: 0.14.0
criproxy_url: "https://github.com/Mirantis/criproxy/releases/download/v{{ criproxy_version }}/criproxy"
#criproxy_source_type: "source"
#criproxy_version: b5ca5a6cec278e2054dface4f7a3e111fb9ab84b
#criproxy_url: "https://github.com/Mirantis/criproxy"
virtlet_dest: "{{ base_dest }}/virtlet"
virtlet_source_type: "binary"
virtlet_version: 1.4.4
virtlet_url: "https://github.com/Mirantis/virtlet/releases/download/v{{ virtlet_version }}/virtletctl"
#virtlet_source_type: "source"
#virtlet_version: 68e11b8f1db2c78b063126899f0e60910700975d
#virtlet_url: "https://github.com/Mirantis/virtlet"


istio_dest: "{{ base_dest }}/istio"
istio_source_type: "tarball"
istio_version: 1.0.3
istio_url: "https://github.com/istio/istio/releases/download/{{ istio_version }}/istio-{{ istio_version }}-linux.tar.gz"

go_version: '1.12.5'
kubespray_version: 2.10.4
helm_client_version: 2.9.1
# kud playbooks not compatible with 2.8.0 - see MULTICLOUD-634
ansible_version: 2.7.10
