nameOverride: ""
fullnameOverride: ""

certificateRotateStrategy: {}

# configuration holds kubevirt configurations.  Same as the virt-configMap.
configuration:
  developerConfiguration:
    featureGates:
    - CPUManager

customizeComponents: {}

# imagePullPolicy is the policy to use.
imagePullPolicy: IfNotPresent

# imageRegistry is the image registry to pull the container images
# from. Defaults to the same registry the operator's container image
# is pulled from.
#imageRegistry: ""

# imageTag is the tag to use for the continer images
# installed. Defaults to the same tag as the operator's container
# image.
#imageTag: ""

# infra is the selectors and tolerations that should apply to KubeVirt
# infrastructure components.
#infra: {}

# monitorAccount is the name of the Prometheus service account that
# needs read-access to KubeVirt endpoints. Defaults to prometheus-k8s.
#monitorAccount: ""

# monitorNamespace is the namespace Prometheus is deployed
# in. Defaults to openshift-monitor.
#monitorNamespace: ""

# productName designates the apps.kubevirt.io/part-of label for
# KubeVirt components. Useful if KubeVirt is included as part of a
# product. If ProductName is not specified, the part-of label will be
# omitted.
#productName: ""

# productVersion designates the apps.kubevirt.io/version label for
# KubeVirt components. Useful if KubeVirt is included as part of a
# product. If ProductVersion is not specified, KubeVirt's version will
# be used.
#productVersion: ""

# uninstallStrategy specifies if kubevirt can be deleted if workloads
# are still present. This is mainly a precaution to avoid accidental
# data loss.
#uninstallStrategy: ""

# workloadUpdateStrategy defines at the cluster level how to handle
# automated workload updates.
workloadUpdateStrategy: {}

# workloads contains the selectors and tolerations that should apply
# to KubeVirt workloads.
#workloads: {}
