{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cpu-manager.fullname" . }}-role-binding-daemonset
  labels:
    {{- include "cpu-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cpu-manager.fullname" . }}-daemonset-controller
subjects:
- kind: ServiceAccount
  name: {{ include "cpu-manager.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cpu-manager.fullname" . }}-role-binding-node
  labels:
    {{- include "cpu-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- kind: ServiceAccount
  name: {{ include "cpu-manager.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cpu-manager.fullname" . }}-role-binding-crd
  labels:
    {{- include "cpu-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cpu-manager.fullname" . }}-custom-resource-definition-controller
subjects:
- kind: ServiceAccount
  name: {{ include "cpu-manager.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cpu-manager.fullname" . }}-role-binding-version
  labels:
    {{- include "cpu-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cpu-manager.fullname" . }}-version-controller
subjects:
- kind: ServiceAccount
  name: {{ include "cpu-manager.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cpu-manager.fullname" . }}-role-binding-webhook-installer
  labels:
    {{- include "cpu-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cpu-manager.fullname" . }}-webhook-installer
subjects:
- kind: ServiceAccount
  name: {{ include "cpu-manager.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cpu-manager.fullname" . }}-role-binding-node-lister
  labels:
    {{- include "cpu-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cpu-manager.fullname" . }}-node-lister
subjects:
- kind: ServiceAccount
  name: {{ include "cpu-manager.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
